name: Deployment Pipeline

on:
  push:
    branches:
      - main  # Change if needed

jobs:
  deploy-to-qa:
    name: Deploy to QA
    runs-on: self-hosted  # Runs on Monroe/Azure runner
    environment: QA
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to QA Server
        run: |
          echo "Deploying to QA..."
          # Add your deployment script (Terraform, SCP, Helm, etc.)

  approve-prod:
    name: Approval for Production Deployment
    needs: deploy-to-qa
    runs-on: ubuntu-latest
    environment: Prod
    steps:
      - name: Wait for Manual Approval
        run: echo "Manual approval required in GitHub UI"

  deploy-to-prod:
    name: Deploy to Production
    needs: approve-prod
    runs-on: self-hosted
    environment: Prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Production Server
        run: |
          echo "Deploying to Production..."
          # Add your deployment script here
